apple_app/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

#from .apple_app import views
from . import views

urlpatterns = [
    # ex: /devices/
    url(r'^$', views.index, name='index'),
    # ex: /devices/5/
    url(r'^prices(?P<device_id>\d+)/$', views.detail, name='detail'),
    # ex: /devices/5/results/
]

apple_proj/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'apple_proj.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^', include('apple_app.urls', namespace="apple_app")),
    #url(r'^/', include('bugtracker.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

apple_app/models.py
# coding: utf-8
from django.db import models

class Device(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True, null=True)
    picture_name = models.CharField(max_length=200, blank=True, null=True)
  
    def __unicode__(self):  # Python 3: def __str__(self):
            return self.name

class Usluga(models.Model):
    device = models.ForeignKey(Device)
    service_type = models.CharField(max_length=300, blank=True, null=True)
    service_price = models.DecimalField(max_digits=5, decimal_places=0, blank=True, null=True, default=1000)
    service_time = models.CharField(max_length=200, blank=True, null=True, default='1 час')

    def __unicode__(self):  # Python 3: def __str__(self):
            return self.service_type

apple_app/views.py
from django.shortcuts import render, get_object_or_404
#http://127.0.0.1:8000/%2Fprices1/
from .models import Device


'''def index(request):
    all_device_list = Device.objects.all()
    context = {'all_device_list': all_device_list }
    return render(request, 'apple_app/index_3.html', context)'''
def index(request):
    all_device_list = Device.objects.all()
    device = get_object_or_404(Device, pk=1)
    context = {'all_device_list': all_device_list, 'device': device }
    return render(request, 'apple_app/index_3.html', context)

'''def detail(request, device_id):
    device = get_object_or_404(Device, pk=device_id)
    return render(request, 'apple_app/detail.html', {'device': device})  '''

'''def detail(request, device_id):
    device = get_object_or_404(Device, pk=device_id)
    return render(request, 'apple_app/detail.html', {'device': device,})'''

def detail(request, device_id):
    all_device_list = Device.objects.all()
    device = get_object_or_404(Device, pk=device_id)
    context = {'all_device_list': all_device_list, 'device': device }
    return render(request, 'apple_app/index_3.html', context)

apple_app/templates/apple_app/index_3.html
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Ремонт iPhone</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'apple_app' %}/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'apple_app' %}/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'apple_app' %}/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static 'apple_app' %}/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'apple_app:detail' device.id %}">Ремонт iPhone</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">     Цены на ремонт <span class="caret"></span>
                  </a>
                    <ul class="dropdown-menu">
                      {% for device in all_device_list %}
                        <li class="dropdown"><a href="{% url 'apple_app:detail' device.id %}#device">{{ device.name }}</a></li>
                      {% endfor %}
                    </ul>
                </li>
                    
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="#contact">Москва Горбушка Багратионовский проезд 7</a></li>
                <li><a href="#contact">Тел. +7(495)-230-02-26</a></li>
            </div>

          </div>
        </nav>
      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li class="" data-target="#myCarousel" data-slide-to="1"></li>
        <li class="" data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'apple_app' %}/images/car1.jpg" alt="First slide" >
          <div class="container">
            <div class="carousel-caption">
              <h1>Телефон +7(495)-000-00-00.</h1>
              <p>Мы находимся по адресу:
                Метро Багратионовская горбушкин двор
                Павильон А01-017А.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Открыть карту проезда</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'apple_app' %}/images/car2.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Купим</h1>
              <p>технику apple, можно неисправную, на запчасти.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Открыть карту проезда</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'apple_app' %}/images/car1.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Телефон +7(495)-000-00-00.</h1>
              <p>Мы находимся по адресу:
                Метро Багратионовская горбушкин двор
                Павильон А01-017А.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Открыть карту проезда</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    
	<div class="container marketing">

      <!-- START THE FEATURETTES -->
      
      <div class="row featurette">
        <div class="col-md-7"><a name="device"></a>
          <h2 class="featurette-heading">{{ device.name }}</h2>
        </div>
      <div class="row featurette">
        <div class="col-md-7">
            <table class="table">
              <thead>
              <tr>
                 <th>Ваша проблема</th>
                 <th>Цена</th>
                 <th align="center">Время ремонта</th>
                </tr>
              </thead>

            {% for usluga in device.usluga_set.all %}
              <tr>
                <td>{{ usluga.service_type }}</td>
                <td align="center">{{ usluga.service_price }}</td>
                <td align="center">{{ usluga.service_time }}</td>
              </tr>   
            {% endfor %}         
            </table>
        </div>
        <div class="col-md-5">
          <img  data-holder-rendered="true" src="{% static 'apple_app' %}/images/{{ device.picture_name }}" alt="500x500">
        </div>
      </div>

      <hr class="featurette-divider">

      
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/1.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Запчасти</h2>
          <p>Только качественные запчасти. Ваш iPhone будет как новый.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/2.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Гарантия</h2>
          <p>Даем гарантию на все выполненные работы.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/3.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Скорость</h2>
          <p>Выполняем ремонт всего за один день. Большинство ремонтов занимает менее часа</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/4.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Опыт</h2>
          <p>Большой опыт ремонта iPhone. Более 5 лет на рынке.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

      <!-- /END THE FEATURETTES -->
	  
      <hr class="featurette-divider">

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Наверх</a></p>
        <p>© 2015 Ремонт iPhone. · <a href="#">Москва Горбушка Багратионовский проезд 7 (Павильон А1-017а)</a> · <a href="#">тел. +7(495)232-06-22</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'apple_app' %}/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'apple_app' %}/bootstrap.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'apple_app' %}/holder.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'apple_app' %}/ie10-viewport-bug-workaround.js"></script>
  

<svg style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;" preserveAspectRatio="none" viewBox="0 0 500 500" height="500" width="500"><defs><style type="text/css"></style></defs><text style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif" y="25" x="0">500x500</text></svg></body></html>

apple_app/templates/apple_app/index_3_backup.html
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Ремонт iPhone</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href="{% static 'apple_app' %}/bootstrap.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'apple_app' %}/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'apple_app' %}/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="{% static 'apple_app' %}/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'apple_app:detail' device.id %}">Ремонт iPhone</a>
            </div>

            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
               {% for device in all_device_list %}
                <li><a href="{% url 'apple_app:detail' device.id %}#device">{{ device.name }}</a></li>
                <!--<li><a href="#device">{{ device.name }}</a></li>-->
               {% endfor %}
                <li><a href="#contact">Москва Ленина 61 офис 601</a></li>
                <li><a href="#contact">Тел. +7(495)-230-02-26</a></li>    
              </ul>
            </div>

          </div>
        </nav>
      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li class="" data-target="#myCarousel" data-slide-to="1"></li>
        <li class="" data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'apple_app' %}/images/car2.jpg" alt="First slide" >
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'apple_app' %}/images/car2.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'apple_app' %}/images/car2.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->
    
	
	<div class="container marketing">

      <!-- START THE FEATURETTES -->
      
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">{{ device.name }}</h2>
        </div>
      <div class="row featurette">
        <div class="col-md-7">
            <table class="table">
              <thead>
              <tr>
                 <th>Ваша проблема</th>
                 <th>Цена</th>
                 <th align="center">Время ремонта</th>
                </tr>
              </thead>

            {% for usluga in device.usluga_set.all %}
              <tr>
                <td>{{ usluga.service_type }}</td>
                <td align="center">{{ usluga.service_price }}</td>
                <td align="center">{{ usluga.service_time }}</td>
              </tr>   
            {% endfor %}         
            </table>
        </div>
        <div class="col-md-5">
          <img  data-holder-rendered="true" src="{% static 'apple_app' %}/images/{{ device.picture_name }}" alt="500x500">
        </div>
      </div>

      <hr class="featurette-divider">

      
      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/1.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Запчасти</h2>
          <p>Только качественные запчасти. Ваш iPhone будет как новый.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/2.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Гарантия</h2>
          <p>Даем гарантию на все выполненные работы.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/3.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Скорость</h2>
          <p>Выполняем ремонт всего за один день. Большинство ремонтов занимает менее часа</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-circle" src="{% static 'apple_app' %}/images/4.png" alt="Generic placeholder image" height="140" width="140">
          <h2>Опыт</h2>
          <p>Большой опыт ремонта iPhone. Более 5 лет на рынке.</p>
          <!--<p><a class="btn btn-default" href="#" role="button">View details »</a></p>-->
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

      <!-- /END THE FEATURETTES -->
	  
      <hr class="featurette-divider">

      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#">Наверх</a></p>
        <p>© 2015 Ремонт iPhone. · <a href="#">Москва Ленина 61 офис 601</a> · <a href="#">тел. +7(495)232-06-22</a></p>
      </footer>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'apple_app' %}/jquery.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'apple_app' %}/bootstrap.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'apple_app' %}/holder.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'apple_app' %}/ie10-viewport-bug-workaround.js"></script>
  

<svg style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;" preserveAspectRatio="none" viewBox="0 0 500 500" height="500" width="500"><defs><style type="text/css"></style></defs><text style="font-weight:bold;font-size:25pt;font-family:Arial, Helvetica, Open Sans, sans-serif" y="25" x="0">500x500</text></svg></body></html>